### ISSUE TITLE
Matching rake spec files (for Rails applications)

### ISSUE THREAD

**Issue by russCloak** [cyphactor/alt#10]
New scenario here where Alt cannot find the alternate:

File exists at `lib/tasks/something.rake`
Test file exists at `spec/lib/tasks/something_rake_spec.rb`

From `something.rake`, alt finds the spec file, but from the spec file it cannot find an alternate. 

Here's the debug output:

Rake file:
```
$ alt --debug lib/tasks/intercom.rake
0.08695652173913043: lib/tasks/intercom.rake - spec/controllers/intercom_proxy_controller_spec.rb
0.08804347826086957: lib/tasks/intercom.rake - spec/lib/intercom/batch_enqueuer_spec.rb
0.09518213866039954: lib/tasks/intercom.rake - spec/lib/intercom/bulk_pusher_spec.rb
0.11360448807854139: lib/tasks/intercom.rake - spec/lib/intercom/leads_spec.rb
0.07012622720897616: lib/tasks/intercom.rake - spec/lib/notification_preferences/intercom_preferences_spec.rb
0.391304347826087: lib/tasks/intercom.rake - spec/lib/tasks/intercom_rake_spec.rb
0.11148272017837234: lib/tasks/intercom.rake - spec/queues/intercom/push_batch_spec.rb
path to find alternate for: lib/tasks/intercom.rake
# possible alternate paths: 3100
# filtered possible alternate paths: 7
highest_score: 0.391304347826087
highest_scored_poss_alt_path: spec/lib/tasks/intercom_rake_spec.rb
spec/lib/tasks/intercom_rake_spec.rb
```

Test file:
```
alt --debug spec/lib/tasks/intercom_rake_spec.rb
path to find alternate for: spec/lib/tasks/intercom_rake_spec.rb
# possible alternate paths: 3100
# filtered possible alternate paths: 0
highest_score: 0
highest_scored_poss_alt_path:
```

The reasoning is fairly obvious, it's just because the spec/implementation file names aren't similar enough, or are just kind of structured differently... In any case, it *could* be a simple matter of adding an exception, but I'm wondering if there's a smarter way to solve it. 

I was kind of surprised it couldn't find a possible alternate path to search though... does that make sense to anyone else?

**Comment by cyphactor** [comment]
@russCloak this has been resolved in **master**. Please pull the latest version.
