### ISSUE TITLE
Improve the vim script

### ISSUE THREAD

**Issue by russCloak** [cyphactor/alt#9]
I think it'd be beneficial to craft a nice vim script (which I suppose would be a plugin) for this.

I'm sure there are other things people would like, but the one that's bothering me at the moment is:

1. Check buffer for alt file before using `:edit` to open it (this would preserve location in the file)

**Comment by cyphactor** [comment]
I added this question and answer to a new https://github.com/cyphactor/alt/wiki/Frequently-Asked-Questions#how-do-i-get-vim-to-remember-cursor-position-when-alternating wiki page. Therefore, I am going to close this issue.
